### ISSUE TITLE
Errors when building with yarn

### ISSUE THREAD

**Issue by BjoernPetersen** [FelixGail/Musicbot-web#7]
Running `yarn` in the project directory leads to an error. Apparently some dependency requires Python2?

```
yarn                                                                        yarn install v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.0.7: The platform "win32" is incompatible with this module.
info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.1: The platform "win32" is incompatible with this module.
info "fsevents@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "workspace-aggregator-b5a0013b-ba33-4d90-9feb-f0faf6567b8e > client > react-scripts > @typescript-eslint/eslint-plugin@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
warning "workspace-aggregator-b5a0013b-ba33-4d90-9feb-f0faf6567b8e > client > react-scripts > @typescript-eslint/parser@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
[4/4] Building fresh packages...
[-/3] ⠠ waiting...                                                                                  [2/3] ⠠ node-sass                                                                                   error E:\JMusic\MusicBot-web\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: E:\JMusic\MusicBot-web\node_modules\node-sass
Output:
Building: C:\Users\Bjoern\scoop\apps\nodejs\current\node.exe E:\JMusic\MusicBot-web\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Users\\Bjoern\\scoop\\apps\\nodejs\\current\\node.exe',
gyp verb cli   'E:\\JMusic\\MusicBot-web\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@13.1.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\JMusic\MusicBot-web\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\JMusic\MusicBot-web\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\JMusic\MusicBot-web\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\JMusic\MusicBot-web\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\JMusic\MusicBot-web\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\JMusic\MusicBot-web\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\JMusic\MusicBot-web\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\JMusic\MusicBot-web\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\JMusic\MusicBot-web\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\JMusic\MusicBot-web\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\JMusic\MusicBot-web\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\JMusic\MusicBot-web\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n' +
gyp verb `which` failed     '    at getNotFoundError (E:\\JMusic\\MusicBot-web\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F (E:\\JMusic\\MusicBot-web\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E (E:\\JMusic\\MusicBot-web\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at E:\\JMusic\\MusicBot-web\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at E:\\JMusic\\MusicBot-web\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at E:\\JMusic\\MusicBot-web\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\Bjoern\scoop\apps\python\current\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Bjoern\scoop\apps\python\current\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:295:12)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at maybeClose (internal/child_process.js:1028:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Users\\Bjoern\\scoop\\apps\\nodejs\\current\\node.exe" "E:\\JMusic\\MusicBot-web\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\JMusic\MusicBot-web\node_modules\node-sass
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by FelixGail** [comment]
obsolete
